### ISSUE TITLE
Balearic Islands map

### ISSUE THREAD

**Issue by Vidcom** [Svetroid/Riskrieg#11]
![image](https://user-images.githubusercontent.com/7198424/102384854-12b6a900-3fc5-11eb-88a8-2fb09cdf205a.png)

submitted by Blu3 (Sula Feet Studios) 2020/05/05

**Comment by Svetroid** [comment]
Rejected.
Reason: Too small and uninteresting, as well as too many other similar maps in the game at the time of this comment.
